USE [AZA]
GO

EXEC [dbo].[usp_InsertDelivery]
    @delivery_cd = 'CD0012',
    @delivery_nm1 = 'Delivery Name 1',
    @delivery_kn1 = 'Delivery Kana 1',
    @delivery_nm2 = 'Delivery Name 2',
    @delivery_kn2 = 'Delivery Kana 2',
    @zip_cd = '12345678',
    @prefecture_cd = '01',
    @city_nm = 'City Name',
    @town_nm = 'Town Name',
    @apartment_nm = 'Apt Name',
    @address1 = 'Address Line 1',
    @address2 = 'Address Line 2',
    @tel = '123-456-7890',
    @fax = '987-654-3210',
    @delivery_class_1 = '999',
    @delivery_class_2 = '999',
    @delivery_class_3 = '999',
    @remark = 'This is a test remark.',
    @cre_user = 'TestUser',
    @cre_prg = 'TestProgram',
    @cre_ip = '127.0.0.1',
    @cre_date = NULL,
    @upd_user = NULL,
    @upd_prg = NULL,
    @upd_ip = NULL,
    @upd_date = NULL,
    @del_user = NULL,
    @del_prg = NULL,
    @del_ip = NULL,
    @del_date = NULL,
    @del_flg = 0;

EXEC [dbo].[usp_UpdatetDelivery]
    @delivery_cd = 'CD0012',
    @delivery_nm1 = 'Delivery Name 1',
    @delivery_kn1 = 'Delivery Kana 1',
    @delivery_nm2 = 'Delivery Name 2',
    @delivery_kn2 = 'Delivery Kana 2',
    @zip_cd = '5435452',
    @prefecture_cd = '01',
    @city_nm = 'City Name',
    @town_nm = 'Town Name',
    @apartment_nm = 'Apt Name',
    @address1 = 'Address Line 1',
    @address2 = 'Address Line 2',
    @tel = '123-456-7890',
    @fax = '987-654-3210',
    @delivery_class_1 = '999',
    @delivery_class_2 = '999',
    @delivery_class_3 = '999',
    @remark = 'This is a test remark.',
    @upd_user = NULL,
    @upd_prg = NULL,
    @upd_ip = NULL,
    @upd_date = NULL,
    @del_user = NULL,
    @del_prg = NULL,
    @del_ip = NULL,
    @del_date = NULL,
    @del_flg = 0; 

SELECT * FROM [dbo].[m_delivery] WHERE [delivery_cd] = 'CD0011';

